import type { Metadata } from 'next'
import { Outfit } from 'next/font/google'
import '../styles/globals.css'
import { Web3Provider } from '@/providers/web3.provider'
import { SpeedInsights } from '@vercel/speed-insights/next'
import { Analytics } from '@vercel/analytics/next'

const outfit = Outfit({
  subsets: ['latin'],
  weight: ['400', '500', '700'],
})

export const metadata: Metadata = {
  title: 'Claim',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={`${outfit.className} antialiased`}>
        <Web3Provider>
          {children}
          <SpeedInsights />
          <Analytics />
        </Web3Provider>
      </body>
    </html>
  )
}
